### ISSUE TITLE
How to use with raspberry ?

### ISSUE THREAD

**Issue by luisfosoares** [kounch/homebridge-mitsubishi-vac-ir#2]
Hello, 

How can i use this with raspberry? 

What is the exactly sensor needed? Any procedure already written about this? 

Thanks for the help, noob guy here

**Comment by kounch** [comment]
Besides the system with homebridge installed, you need an Arduino board, with a temperature sensor (LM35) or a temperature and humidity sensor (DHT22) and a 940nm IR LED (VS1838B).

You can connect the Arduino board directly via USB to the raspberry pi, or use a WiFi connection with a ESP8266 module.

Software for the arduino board can be downloaded here:
https://github.com/kounch/homebridge_mitsubishi_ir_arduino

An example sketch is available here:
https://github.com/kounch/Homebridge-Mitsubishi-IR

**Comment by luisfosoares** [comment]
Ok I ordered the material will try and if it able I close the issue

**Comment by kounch** [comment]
Closed for inactivity
